
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] ||= 'db' %>
  port: 5432

development:
  <<: *default
  database: <%= ENV['DB_NAME'] ||= 'sample_api_development' %>
test:
  <<: *default
  database: sample_api_test

#
staging:
  <<: *default
  database: sample_api_staging

develop:
  <<: *default
  database: sample_api_develop

production:
  <<: *default
  database: sample_api_production
